### ISSUE TITLE
Not Working In Android 10 

### ISSUE THREAD

**Issue by rahat14** [wangchen11/XQCEditor#1]
Permission Error When compile c code

**Comment by wangchen11** [comment]
只能将targetSdk降低到28以下，除非google修改selinux策略。 检查一下targetSdk。
------
You can only reduce targetsdk below 28 unless Google modifies the SELinux policy.
Check the targetSdk

**Comment by rahat14** [comment]
i needed to build a compiler for google play store release , But i think play store not support 28 . can you cross check it? . also from this https://developer.android.com/distribute/best-practices/develop/target-sdk doc.

**Comment by wangchen11** [comment]
You can only reduce targetsdk below 28. No other way.
