### ISSUE TITLE
发现一个bug:
使用.c文件时,不能#include<complex.h>

### ISSUE THREAD

**Issue by kexinadm** [wangchen11/XQCEditor#2]
系统: 安卓 8.1.0
软件: 快写 2.3.1

在用".c"文件时 不能包含<complex.h>,

".cpp"文件则可以包含该头文件![Screenshot_2022-05-20-20-07-50-25.png](https://user-images.githubusercontent.com/95196177/169525635-300769e9-c839-477f-9a47-ed65761e5c9c.png)
![Screenshot_2022-05-20-20-14-29-91.png](https://user-images.githubusercontent.com/95196177/169526029-ff58700f-4876-485e-b9e5-7399f411776f.png)

**Comment by wangchen11** [comment]
不需要修复
