### ISSUE TITLE
主函数 命令行 传参, argc值可能不正确

### ISSUE THREAD

**Issue by kexinadm** [wangchen11/XQCEditor#3]
![Screenshot_2022-05-20-20-46-28-51.png](https://user-images.githubusercontent.com/95196177/169530989-467b3681-00cb-4226-b581-cff7025912bb.png)

![Screenshot_2022-05-20-20-30-01-93.png](https://user-images.githubusercontent.com/95196177/169531041-4ab21086-c3a6-41c6-8711-1bdecadf4695.png)
![Screenshot_2022-05-20-20-30-06-41.png](https://user-images.githubusercontent.com/95196177/169531066-6a0c6470-2c5b-4ce2-944c-355c0e27f198.png)
![Screenshot_2022-05-20-20-46-12-94.png](https://user-images.githubusercontent.com/95196177/169531093-ee5e6c97-eda1-4da1-861d-8980bcce5c39.png)

系统: Android   8.1.0
软件: 快写代码 2.3.1

请问 这里是否出了问题 ,还是我的使用方式不对？

**Comment by wangchen11** [comment]
fixed
